const products = [
	{
		id: 1,
		name: 'Product 1',
		slug: 'product-1',
		price: 30.5,
		inStock: true,
		featuredImage: 'https://via.placeholder.com/400x400',
		images: [],
		category: 'Category 1',
		featured: true,
		ratings: 4.5,
		quantity: 8,
		description: 'Product description',
	},
	{
		id: 2,
		name: 'Product 2',
		slug: 'product-2',
		price: 50.5,
		inStock: true,
		featuredImage: 'https://via.placeholder.com/400x400',
		images: [],
		category: 'Category 2',
		featured: true,
		ratings: 3.5,
		quantity: 80,
		description: 'Product description',
	},
	{
		id: 3,
		name: 'Product 3',
		slug: 'product-3',
		price: 100.0,
		inStock: true,
		featuredImage: 'https://via.placeholder.com/400x400',
		images: [
			'https://via.placeholder.com/200x200',
			'https://via.placeholder.com/200x200',
		],
		category: 'Category 3',
		featured: true,
		ratings: 4.0,
		quantity: 10,
		description: 'Product description',
	},
	{
		id: 4,
		name: 'Product 4',
		slug: 'product-4',
		price: 20.5,
		inStock: true,
		featuredImage: 'https://via.placeholder.com/400x400',
		images: [],
		category: 'Category 3',
		featured: true,
		ratings: 3.0,
		quantity: 80,
		description: 'Product description',
	},
];

module.exports = products;
